axis_linear: 4  # Right thumb stick vertical 
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 3  # Righ thumb stick horizontal
scale_angular: 0.4

enable_button: 4  # Left trigger button (LB)
enable_turbo_button: 5  # Right trigger button (RB)